spring:
  application:
    name: seed-desafio-cdc
  datasource:
    url: jdbc:postgresql://localhost:5432/seed_desafio_cdc
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
